### ISSUE TITLE
Should be a way to rotate a selection of multiple cubes by an exact amount (snapping, etc) instead of just the gizmo's analog input

### ISSUE THREAD

**Issue by parzivail** [Dumb-Code/DumbCode-Studio#177] opened 2021-02-19 00:07 UTC

**Comment by NeusFear** [comment] 2021-02-19 00:08
send a gif, because this might be intentional

**Comment by parzivail** [comment] 2021-02-19 00:24
On second thought it's probably intentional, so I'll update the title to better reflect my thoughts

**Comment by NeusFear** [comment] 2021-09-07 16:38
duplicate of #13

**Closed by NeusFear** 2021-09-07 16:38 UTC
Labels: enhancement, animator, modeler
