### ISSUE TITLE
Add disclaimer for when exiting studio

### ISSUE THREAD

**Issue by BrownBoiiWonder** [Dumb-Code/DumbCode-Studio#57] opened 2020-12-15 05:02 UTC
![image](https://user-images.githubusercontent.com/3739555/102173282-88990400-3e4f-11eb-9d06-97309d8476bf.png)

Basically a disclaimer to make the user save/export/backup any open projects that they want to save.

**Comment by NeusFear** [comment] 2020-12-18 19:38
duplicate of #46

**Closed by NeusFear** 2020-12-18 19:38 UTC
Labels: enhancement
